rules:
    default:
        protection:
            required_pull_request_reviews:
                required_approving_review_count: 1
                dismiss_stale_reviews: true
            required_status_checks:
                contexts:
                - continuous-integration/travis-ci
        enabling_label: enable-mergify
        disabling_label: null
        disabling_files:
        - .mergify.yml
        - .travis.yml
    branches:
        master: null
