language: python

python:
  - "3.4"

cache:
  directories:
    - tmp/.pip-cache/

install:
  - travis_retry pip install invoke
  - travis_retry invoke install --upgrade --wheel-repo=https://github.com/CenterForOpenScience/wheelhouse

before_script:
  - invoke flake

script:
  - invoke test

notifications:
  flowdock: 9f8a6baf3feafdb62e515718698d06d0
