# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install invoke
    - invoke requirements
    - invoke addon_requirements

# command to run tests, e.g. python setup.py test
script: invoke test_all
