language: python

python:
  - "3.4"

sudo: false

cache:
  directories:
    - $HOME/pip-cache
    - $HOME/wheelhouse

before_install:
    - export WHEELHOUSE=$HOME/wheelhouse
    - export PIP_CACHE=$HOME/pip-cache

install:
    - travis_retry pip install invoke
    - travis_retry invoke wheelhouse
    - travis_retry invoke install --develop

env:
  - WATERBUTLER_CONFIG=./travis-config.json

before_script:
  - invoke flake

script:
  - invoke test

notifications:
  flowdock: 9f8a6baf3feafdb62e515718698d06d0
