# Config file for automatic testing at travis-ci.org

language: python
services: 
    - mongodb
    - elasticsearch

python:
  - "2.7"

before_install:
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.deb && sudo dpkg -i elasticsearch-1.1.1.deb && sudo service elasticsearch restart

install:
    - cp website/settings/local-travis.py website/settings/local.py
    - pip install invoke
    - invoke requirements
    - invoke addon_requirements --mfr 0

script: invoke test_all
