
version: "3"

services:
  requirements:
    volumes:
      - code:/code:nocopy
  assets:
    volumes:
      - code:/code:nocopy
  admin_assets:
    volumes:
      - code:/code:nocopy
  sharejs:
    volumes:
      - code:/code:nocopy
  worker:
    volumes:
      - code:/code:nocopy
  admin:
    volumes:
      - code:/code:nocopy
  web:
    volumes:
      - code:/code:nocopy
  api:
    volumes:
      - code:/code:nocopy

# Additional configuration for development on services linked with osf.io

#  fakecas:
#    image: quay.io/centerforopenscience/fakecas:latest
#    command: fakecas -host=0.0.0.0:8080 -dbaddress=172.19.0.7:27017

  wb:
    volumes:
      - wb-sync:/code:nocopy

#  wb_worker:
#    volumes:
#      - wb-sync:/code:nocopy

#  wb_requirements:
#    volumes:
#      - wb-sync:/code:nocopy

#  mfr:
#    volumes:
#      - mfr-sync:/code:nocopy

#  mfr_requirements:
#    volumes:
#      - mfr-sync:/code:nocopy

#  preprints:
#    volumes:
#      - preprints-sync:/nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - preprints_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link ember-osf && yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4200"

#  registries:
#    volumes:
#      - registries-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - registries_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link ember-osf && yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4300"


#  # Use this for ember-osf linked development (with docker-sync):
#  emberosf:
#    build: ../ember-osf
#    command: /bin/bash -c "yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false"
#    volumes:
#      - ember-osf-sync:/code:nocopy


volumes:
  code:
    external: true

#  wb-sync:
#    external: true

#  mfr-sync:
#    external: true

#  ember-osf-sync:
#    external: true

