# Alias localhost in order to allow docker containers
# access your machines loopback interface (127.0.0.1).
#
# sudo ifconfig lo0 alias 192.168.168.167

# Settings (default osf configuration settings)
#
# cp ./website/settings/local-dist.py ./website/settings/local.py

# Setup / Update the shared Python site-packages environment
#
# docker-compose up requirements

# Configure remote debugging and environment variables
# by modifying the .docker-compose.env file.
#
# WEB_REMOTE_DEBUG=192.168.168.167:11000
# API_REMOTE_DEBUG=192.168.168.167:12000
# WORKER_REMOTE_DEBUG=192.168.168.167:13000

# Run services (assets can take up to 10 minutes the first run)
#
# docker-compose up elasticsearch tokumx fakecas assets

# Run the OSF
#
# docker-compose up web api

# Resetting persistent storage volumes
#
# e.g.
# docker-compose stop -t 0 tokumx
# docker-compose rm tokumx
# docker volume rm [projectname]_tokumx_volume

# Using IPDB
# You can detach from a container and leave it running using the CTRL-p CTRL-q key sequence.
#
# docker attach [projectname]_web_1


version: '2'
volumes:
  requirements_volume:
    external: false
  tokumx_volume:
    external: false
  elasticsearch_volume:
    external: false

services:
  requirements:
    image: quay.io/centerforopenscience/osf:develop
    command: /bin/bash -c "invoke requirements --quick && cp -Rf /usr/local/lib/python2.7/site-packages /"
    restart: 'no'
    volumes:
      - requirements_volume:/site-packages
      - ./:/code

  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data

#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - 5672:5672
#      - 15672:15672

#  postgres:
#    image: postgres
#    command: /bin/bash -c "sed -i -e 's/max_connections.*/max_connections = 5000/' /var/lib/postgresql/data/postgresql.conf || true && sed -i -e 's/#log_min_duration_statement = .*/log_min_duration_statement = 0/' /var/lib/postgresql/data/postgresql.conf || true && /docker-entrypoint.sh postgres"
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: osf

  tokumx:
    image: quay.io/centerforopenscience/tokumx:latest
    command: mongod --ipv6
    ports:
      - 27017:27017
    environment:
      TOKU_HUGE_PAGES_OK: 1
    volumes:
      - tokumx_volume:/data/db

  fakecas:
    image: quay.io/centerforopenscience/fakecas:latest
    command: fakecas -host=0.0.0.0:8080 -dbaddress=tokumx:27017
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - tokumx
    links:
      - tokumx

#  flower:
#    image: quay.io/centerforopenscience/osf:develop
#    command: python manage.py celery flower
#    depends_on:
#      - rabbitmq
#    links:
#      - rabbitmq
#    ports:
#      - 5555:5555
#    environment:
#      BROKER_URL: amqp://guest:guest@rabbitmq:5672/

#  beat:
#    image: quay.io/centerforopenscience/osf:develop
#    command: invoke celery_beat
#    depends_on:
#      - tokumx
#      - rabbitmq
#      - elasticsearch
#    links:
#      - tokumx
#      - rabbitmq
#      - elasticsearch
#    volumes:
#      - requirements_volume:/usr/local/lib/python2.7/site-packages
#      - ./:/code
#    environment:
#      DB_HOST: tokumx
#      ELASTIC_URI: elasticsearch:9200
#      BROKER_URL: amqp://guest:guest@rabbitmq:5672/

#  worker:
#    image: quay.io/centerforopenscience/osf:develop
#    command: invoke celery_worker
#    restart: unless-stopped
#    depends_on:
#      - tokumx
#      - rabbitmq
#      - elasticsearch
#    links:
#      - tokumx
#      - rabbitmq
#      - elasticsearch
#    volumes:
#      - requirements_volume:/usr/local/lib/python2.7/site-packages
#      - ./:/code
#    environment:
#      C_FORCE_ROOT: 1
#      DB_HOST: tokumx
#      ELASTIC_URI: elasticsearch:9200
#      BROKER_URL: amqp://guest:guest@rabbitmq:5672/

  assets:
    image: quay.io/centerforopenscience/osf:develop
    command: invoke assets -dw
    restart: unless-stopped
    volumes:
      - requirements_volume:/site-packages
      - ./:/code

  web:
    image: quay.io/centerforopenscience/osf:develop
    command: invoke server -h 0.0.0.0
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - tokumx
#      - rabbitmq
      - elasticsearch
      - fakecas
    links:
      - tokumx
#      - rabbitmq
      - elasticsearch
      - fakecas
    env_file:
      - .docker-compose.env
    stdin_open: true
    tty: true
    volumes:
      - requirements_volume:/usr/local/lib/python2.7/site-packages
      - ./:/code

  api:
    image: quay.io/centerforopenscience/osf:develop
    command: invoke apiserver -h 0.0.0.0  # --remote 192.168.168.167:12000
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - tokumx
#      - rabbitmq
      - elasticsearch
      - fakecas
    links:
      - tokumx
#      - rabbitmq
      - elasticsearch
      - fakecas
    env_file:
      - .docker-compose.env
    stdin_open: true
    tty: true
    volumes:
      - requirements_volume:/usr/local/lib/python2.7/site-packages
      - ./:/code
