
version: "3"

services:
  requirements:
    volumes:
      - code:/code:nocopy
  assets:
    volumes:
      - code:/code:nocopy
  admin_assets:
    volumes:
      - code:/code:nocopy
  sharejs:
    volumes:
      - code:/code:nocopy
  worker:
    volumes:
      - code:/code:nocopy
  admin:
    volumes:
      - code:/code:nocopy
  web:
    volumes:
      - code:/code:nocopy
  api:
    volumes:
      - code:/code:nocopy

# Additional configuration for development on services linked with osf.io

#  fakecas:
#    image: quay.io/centerforopenscience/fakecas:latest
#    command: fakecas -host=0.0.0.0:8080 -dbaddress=172.19.0.7:27017

#  wb:
#    volumes:
#      - container:wb-sync

#  wb_worker:
#    volumes:
#      - container:wb-sync

#  wb_requirements:
#    volumes:
#      - container:wb-sync

#  mfr:
#    volumes:
#      - container:mfr-sync

#  mfr_requirements:
#    volumes:
#      - container:mfr-sync

#  preprints:
#    volumes:
#      - container:preprints-sync
#
#    # Use this for ember-osf linked development (with docker-sync):
#    depends_on:
#      - emberosf
#    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link ember-osf && yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4200"
#    volumes:
#      - preprints_dist_vol:/code/dist
#      - emberosf-sync:/ember-osf

volumes:
  code:
    external: true

#  ember-osf-sync:
#    external: true

