
version: "3"

services:
  requirements:
    volumes:
      - code:/code:nocopy
  assets:
    volumes:
      - code:/code:nocopy
  admin_assets:
    volumes:
      - code:/code:nocopy
  sharejs:
    volumes:
      - code:/code:nocopy
  worker:
    volumes:
      - code:/code:nocopy
  admin:
    volumes:
      - code:/code:nocopy
  web:
    volumes:
      - code:/code:nocopy
  api:
    volumes:
      - code:/code:nocopy

volumes:
  code:
    external: true

